apiVersion: skaffold/v2alpha2
kind: Config
metadata:
  name: skaffold-sync-bug
build:
  artifacts:
  - image: gcr.io/your-project/app
    sync:
      manual:
      - src: 'content.txt'
        dest: /app
deploy:
  kubectl:
    manifests:
    - app.yaml
